### ISSUE TITLE
Allow Synthetic Classes to be Decompiled

### ISSUE THREAD

**Issue by NMcCloudTower** [nbauma109/jd-gui-duo#153]
If a class is marked as synthetic (Class.isSynthetic()) it cannot be properly decompiled.  The program halts after showing the import statements.

**Comment by nbauma109** [comment]
Have you tried switching decompiler? Decompiler bugs must be filed to appropriate decompiler project.

**Comment by NMcCloudTower** [comment]
Will move the issue.
