### ISSUE TITLE
Clicking ok in preferences without modification changes content

### ISSUE THREAD

**Issue by sdhzwc** [nbauma109/jd-gui-duo#75]
First of all, thank you for your efforts. Will multiple languages be supported in the future, such as Chinese

**Comment by sdhzwc** [comment]
Add language selection

**Comment by nbauma109** [comment]
Thanks. The tool is not ready to integrate other languages. That's not in the priorities.

**Comment by sdhzwc** [comment]
> Thanks. The tool is not ready to integrate other languages. That's not in the priorities.

ok 

I didn't set anything, just clicked OK and the content changed. Is this a bug,as follows：
![VeryCapture_20230903163655](https://github.com/nbauma109/jd-gui-duo/assets/46134044/e0c571d0-9396-4a96-ae7f-73d536e5d86f)

**Comment by nbauma109** [comment]
Bug is acknowledged. May I know what is this snipping tool you're using?

**Comment by sdhzwc** [comment]
> 错误已确认。我可以知道你正在使用的这个截图工具是什么吗？

https://verycapture.com/cn/download.html
